version: '3'
services:
  ipfs:
    image: ipfs/go-ipfs:latest
    networks: [mine-dev]
  testrpc:
    image: openmined/sonar-testrpc:edge
    networks: [mine-dev]
  mine:
    image: anoff/test:mine
    entrypoint: "./node_modules/.bin/nodemon bin/cli.js train --mine-address auto --contract-address 0x249c008fc4f9c01248f557985f5b5b1aed8eb98f --ethereum-url http://testrpc:8545 --ipfs-url /ip4/ipfs/tcp/5001"
    networks: [mine-dev]
    depends_on: ["testrpc", "ipfs"]
  notebook:
    image: pysonar-notebook
    networks: [mine-dev]
    ports: ["8888:8888"]
networks:
  mine-dev:
